name: CI Checks
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm exec eslint .

      - name: TypeScript Compilation
        run: pnpm run build

      - name: Run Tests
        run: pnpm test
